### ISSUE TITLE
Namespace might be broken

### ISSUE THREAD

**Issue by Ex3v** [SimPaypl/SimPay-API-php#1]
Hi!

I'm integrating this lib with my Symfony 4 project. I'm having problems with autoloading of this library. 

Steps to reproduce:

```
composer require simpaypl/simpay //installs fine in vendor
```

```php
declare(strict_types=1);

namespace App;

use simpay\Sms;

final class Foo
{
	public function bar() : void
	{
		$sms = new Sms(); //throws error - see below
	}
}
```

Results in the following error:
```
Class 'simpay\Sms' not found
```

This issue might be my local case somehow, although I have pretty default composer and app setup.

Hotfix to this is to add:
```json
"simpay\\": "vendor/simpaypl/simpay/src/"
```
to the `autoload` section of **project** (not this lib) `composer.json`.

Maybe it is just me, or more integration tests of this lib with composer is required and/or fix in namespacing needed.

**Comment by DarkGL** [comment]
Fixed in version 1.2 , clear cache and update library :)

**Comment by Ex3v** [comment]
@DarkGL3  BTW any plans of making this client stateless? 🧅

**Comment by DarkGL** [comment]
@Ex3v with current api no , we have it on roadmap but priority is creating completely new api from scratch :)
