### ISSUE TITLE
Brak kompopnentu

### ISSUE THREAD

**Issue by MESWEB** [SimPaypl/SimPay-API-php#2]
Chcialbym uzyc bibliotek API lecz widze ze plik **Component.php** wymaga **Guzzle, PHP HTTP client** czy nie da sie tego obejsc np zwyklym curlem albo w inny sposob bez angazowania dodatkowych bibliotek komponentow?

**Comment by DarkGL** [comment]
Przyklady uzycia API poprzez curla mozesz sprawdzic tutaj https://docs.simpay.pl/?php#wstep
