### ISSUE TITLE
curl zwraca bledny numer klienta

### ISSUE THREAD

**Issue by MESWEB** [SimPaypl/SimPay-API-php#3]
Uzywam metody curl do odpytania API i zawsze otrzymuje ten sam numer klienta od kilku miesiecy. Dla testow na stronie simpay w panelu gdy generuje testowe SMSy i podaje fake numer wtedy curl zwraca prawidlowy numer tel klienta lecz w gdy prawdziwy klient wysyla formularz to curl zwraca statyczny numer klienta. WYglada to tak jakby numer klienta byl przypisany do odpowiedzi serwera gdy numer klienta nie zostal wygenerowany w panelu.

**Comment by kgrzelak** [comment]
Proszę napisać na k.grzelak@simpay.pl, wysyłając id usługi SMS i przesłać jakieś screenshoty lub/i komendę curl.
Wykonałem testy na jednej z naszych usług testowych przy pomocy programu Postman i zwracane dane są prawidłowe.
![image](https://user-images.githubusercontent.com/51724541/90624530-63d1ae80-e218-11ea-8a23-fbe6229a4aeb.png)

**Comment by MESWEB** [comment]
@kgrzelak Napislem i cisza. Nikt nie odpisuje a ja wciaz jestem ze swoim problemem.
